AddDialog: Show the supported language for each driver.
elementary/switchboard-plug-printers pull request #158
Opened 2022-03-03 16:27 UTC by tintou

2022-03-04 10:33 UTC, jeremypw commented
This PR still results in (apparently) duplicate entries - all with the same language.  Afaict, this is due to faulty logic in the function `private void fetch_ppds (TempDevice temp_device) {` which can add the same driver multiple times.  I you wish I can push a PR to fix this but for now I will leave it to you.

2022-03-04 11:28 UTC, jeremypw requested changes
I think the attribute key for language is `attributes-natural-language` and this is not being handled when the driver is loaded.

2022-03-04 12:08 UTC, jeremypw commented
I've tried adding most of the driver properties to the list and while this resolves some duplicates, there are some HP drivers that differ (afaict) only slightly by the ppd name (`hplip:1/ppd/...` `hplip:2/ppd/...` `hplip:3/ppd/...` etc).  In some cases (not HP) the product name is more informative.

Difficult to know what to do about this. One solution would be to only show recommended drivers by default (with an option to show all).  Also could add a facility to show all available properties for a given driver.  Could check whether the previous make and model was the same but different product name.

2022-03-04 12:33 UTC, jeremypw commented
Example of near duplicate HP Drivers

![HPPrinterDrivers](https://user-images.githubusercontent.com/10513844/156764181-13a58293-7bf4-4428-9c48-b5e2c32fb9f8.png)

2022-05-01 17:12 UTC, jeremypw commented
Need design input regarding how much information to show in the list (see also my comments of 4th Mar above).

2022-05-06 16:18 UTC, andrewdbate commented
Just to add my two cents here, it seems like including the PPD name could be information overload but at the same time there has to be a way to uniquely identify each driver.

Would it be possible to only show the PPD name if it is necessary to make the entry unique?

For example, the above list shows multiple entries for `HP 2000c, hpcups 3.20.3 (en)`. In this case, it is necessary to include the PPD name for each because this is the only way to uniquely identify each entry. However, for `HP 2000C Foomatic/pcl3 (en)` the PPD name does not need to be included because the entry is unique without including it.

Not sure what your thoughts are on this suggestion design-wise.

Either way, it would be good if there was a way to get all information on a particular driver before adding the printer. For example, if there was another panel that shows all information, including the PPD name, for the currently selected driver in the list.

2022-05-31 17:11 UTC, danrabbit commented
Showing everything on one line is indeed a lot and kind of hard to compare. Can we maybe split it up into two lines so you'd get something like:

**HP 2500c, hpcups 3.20.03 (recommended)**
hplip:1/ppd/hplip/HP/hp-2500c.ppd — en

**HP 2500c, hpcups 3.20.03**
hplip:2/ppd/hplip/HP/hp-2500c.ppd — en

**HP 2500c, hpcups 3.20.03**
drv:///hpcups.drv/hp-2500c.ppd — en

Goals here:
* Avoid cutting off information at smaller window widths
* Make it more likely that differentiating information lines up so that it's easier to compare
* Make sure "(recommended)" stands out and isn't buried in between other information
* Use `—` as a separator instead of `()` to more clearly differentiate that the lang code isn't information that is part of a driver name or location/uri/whatever that means. I put it at the end here because it looks like in Jeremy's screenshot that it's not very often differentiating for a row

2022-05-31 17:57 UTC, jeremypw commented
Yes, a design which is necessary for HP printers may be overkill or otherwise sub-optimal for other manufacturers unfortunately but I guess that is inevitable.  Dani's suggestion is a reasonable compromise.

2022-05-31 18:22 UTC, danrabbit commented
We could also switch around the two parts of the bottom line if that's more important. I think that's still not too hard to compare:

**HP 2500c, hpcups 3.20.03 (recommended)**
en — hplip:1/ppd/hplip/HP/hp-2500c.ppd

**HP 2500c, hpcups 3.20.03**
fr — hplip:2/ppd/hplip/HP/hp-2500c.ppd

**HP 2500c, hpcups 3.20.03**
es — drv:///hpcups.drv/hp-2500c.ppd

2022-06-14 16:56 UTC, danrabbit commented on src/Dialogs/AddDialog.vala
> +        // driver_list_store = new ListStore (typeof (DeviceDriver));
```suggestion
```

2022-06-14 16:56 UTC, danrabbit approved these changes
Iterated on the design in the other branch, so this looks good to me

2022-06-15 08:24 UTC, jeremypw approved these changes
LGTM

2022-06-15 15:50 UTC, merged