Port to GTK4
elementary/switchboard-plug-printers pull request #164
Opened 2022-06-12 09:48 UTC by ZenitsuDev

Goes with https://github.com/elementary/switchboard/pull/231

2022-07-11 10:05 UTC, jeremypw commented
There is a difference in alignment of buttons in the Add Print dialog otherwise this seems to match the existing UI well.

 **NEW**
![Screenshot from 2022-07-11 11 03 06](https://user-images.githubusercontent.com/10513844/178240599-856880a0-2477-434d-91a5-c4fe100774ee.png)

**OLD**
![Screenshot from 2022-07-11 11 02 36](https://user-images.githubusercontent.com/10513844/178240604-1a85485f-87ff-4230-89b9-1a4b784c4a23.png)

2022-07-11 10:42 UTC, jeremypw commented
Do references to "gtk30" need changing?

2022-07-31 08:36 UTC, ZenitsuDev commented
sorry for the late response @jeremypw . I will try to update this later. Thank you

2023-01-08 14:08 UTC, treppenwitz03 commented
> There is a difference in alignment of buttons in the Add Print dialog otherwise this seems to match the existing UI well.
> 
> **NEW** ![Screenshot from 2022-07-11 11 03 06](https://user-images.githubusercontent.com/10513844/178240599-856880a0-2477-434d-91a5-c4fe100774ee.png)
> 
> **OLD** ![Screenshot from 2022-07-11 11 02 36](https://user-images.githubusercontent.com/10513844/178240604-1a85485f-87ff-4230-89b9-1a4b784c4a23.png)

This should be fixed now.

2023-01-08 14:10 UTC, treppenwitz03 commented
> There is also a difference in wrapping of the clear all confirmation dialog (at least in English):
> **NEW**
> ![Screenshot from 2022-07-11 11 07 48](https://user-images.githubusercontent.com/10513844/178241389-5db11c8a-1df7-438f-86ef-827d593cac07.png)
> **OLD**
> ![Screenshot from 2022-07-11 11 07 30](https://user-images.githubusercontent.com/10513844/178241391-b33adce4-b7b2-43b2-b6a9-1fab033d07c9.png)

ClearQueueDialog subclasses directly from Granite.MessageDialog so it may be the cause of the wrapping issue.

2023-01-08 14:26 UTC, treppenwitz03 commented
> This ink levels seem to be drawn in accent color regardless of the actual ink color. I faked a printer with only blue (#0000AA) ink:
> 
> **NEW** ![Screenshot from 2022-07-11 11 30 33](https://user-images.githubusercontent.com/10513844/178245454-14458647-2301-4818-9585-92d55984e79c.png) **OLD** ![Screenshot from 2022-07-11 11 30 38](https://user-images.githubusercontent.com/10513844/178245452-4d2c0fa2-05fd-435f-8bce-f3de1005855b.png)

Pardon me about this one, but maybe someone might be able to find the fault in here? I do not a printer right now to be able to test changes I will make. However, looking at the code, the fault I think may lie in the STYLE_CLASS constant in src/Widgets/InkLevel.vala as there might be a change in css node of Gtk.LevelBar.

2023-10-17 22:48 UTC, danirabbit commented on src/Views/SetupView.vala
> +        var pages_modebutton = new Printers.ModeButton ();
This should be radiobuttons instead of a custom widget

2023-10-18 16:53 UTC, danirabbit commented
I think this is ready for another re-review! @jeremypw if you're still interested, let me know if you think this needs to be broken up more to be easier to review.

2023-10-23 17:38 UTC, jeremypw requested changes
I have not yet tested all functionality but notice that the "Add Printer" button remains insensitive after choosing a printer (in master it becomes sensitive under the same conditions)

2023-10-23 20:56 UTC, danirabbit commented
@jeremypw figured out the source of the problem there and ended up rewriting this a bit to use validated entries and give more feedback etc https://github.com/elementary/switchboard-plug-printers/pull/197

2023-10-27 18:25 UTC, danirabbit commented
> Another issue I noticed is that pressing the "Clear All" button only cleared the last job, not all of them.

Fixed! headers and placeholders are considered children here so switched these listbox iterators to use `get_row_at_index` which only includes rows and not headers or placeholders

2023-11-01 19:27 UTC, jeremypw commented
The inklevel indicators do not expand vertically, unlike master so they appear unnecessarily squat (the inks are faked as I do not have a color printer). 

![Screenshot from 2023-11-01 19 23 09](https://github.com/elementary/switchboard-plug-printers/assets/10513844/3ab34c02-f387-45dc-bb5c-bb22a87325f1)
![Screenshot from 2023-11-01 19 23 15](https://github.com/elementary/switchboard-plug-printers/assets/10513844/073ee3a9-2552-4d67-af16-57895a47cf54)

2023-11-01 19:38 UTC, jeremypw commented
I noticed then when printing a test page to a CUPS_BRF PDF printer, the settings for Color/GreyScale and for Portrait/Landscape seemed to have no effect although reversing did.  However the same thing happens in master so not a blocker here.

2024-01-01 20:54 UTC, danirabbit commented
@jeremypw I can also confirm that those settings don't seem to do anything for a PDF printer, but like you said the problem also exists in the current master and that code wasn't touched in this branch

It looks like the other issue with the ink levelbars was fixed though!

2024-01-22 14:51 UTC, jeremypw requested changes
Nearly everything works except removing a printer does not actually remove it until the plug is closed (regression from master which removes the printer and refreshes the list straightaway.

2024-02-07 12:58 UTC, jeremypw approved these changes

2024-02-07 12:58 UTC, merged